cmake -DBPFTIME_ENABLE_UNIT_TESTING=YES -DBPFTIME_LLVM_JIT=NO -DBPFTIME_BUILD_EXECUTABLE=YES -DCMAKE_MESSAGE_LOG_LEVEL=DEBUG -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DFRIDA_DOWNLOAD_URL_PREFIX:STRING=https://ghproxy.com/ -S. -Bbuild
cmake --build build --config Debug --target all -j
