ignore:
  - "third_party"

coverage:
  status:
    project:
      default:
        target: auto
        # adjust accordingly based on how flaky your tests are
        # this allows a 0.5% drop from the previous base commit coverage
        threshold: 0.5%
    patch:
      default:
        target: auto
        base: auto
        threshold: 0.5%
        only_pulls: false