static const char TRAMPOLINE_PTX[] = R"(
//
// Generated by LLVM NVPTX Back-End
//

.version 8.1
.target sm_61
.address_size 64

	// .globl	spin_lock               // -- Begin function spin_lock
.extern .func  (.param .b32 func_retval0) vprintf
(
	.param .b64 vprintf_param_0,
	.param .b64 vprintf_param_1
)
;
.visible .const .align 8 .u64 constData;
.visible .const .align 8 .b8 map_info[10240];
.global .align 1 .b8 _$_str[139] = {87, 65, 82, 78, 73, 78, 71, 58, 32, 103, 101, 116, 71, 108, 111, 98, 97, 108, 84, 104, 114, 101, 97, 100, 73, 100, 40, 37, 108, 117, 41, 32, 101, 120, 99, 101, 101, 100, 115, 32, 109, 97, 120, 95, 116, 104, 114, 101, 97, 100, 95, 99, 111, 117, 110, 116, 32, 40, 37, 108, 117, 41, 32, 111, 102, 32, 109, 97, 112, 32, 37, 108, 117, 44, 32, 112, 108, 101, 97, 115, 101, 32, 115, 101, 116, 32, 66, 80, 70, 84, 73, 77, 69, 95, 77, 65, 80, 95, 71, 80, 85, 95, 84, 72, 82, 69, 65, 68, 95, 67, 79, 85, 78, 84, 32, 97, 116, 32, 115, 121, 115, 99, 97, 108, 108, 45, 115, 101, 114, 118, 101, 114, 32, 115, 105, 100, 101, 10, 0};
.global .align 1 .b8 _$_str1[50] = {67, 97, 108, 108, 105, 110, 103, 32, 98, 112, 102, 95, 112, 101, 114, 102, 95, 101, 118, 101, 110, 116, 95, 111, 117, 116, 112, 117, 116, 32, 111, 110, 32, 117, 110, 115, 117, 112, 112, 111, 114, 116, 101, 100, 32, 109, 97, 112, 33, 0};
.global .align 1 .b8 _$_str2[45] = {107, 101, 114, 110, 101, 108, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 101, 110, 116, 101, 114, 101, 100, 44, 32, 109, 101, 109, 61, 37, 108, 120, 44, 32, 109, 101, 109, 115, 122, 61, 37, 108, 100, 10, 0};
.global .align 1 .b8 __const_$_bpf_main_$_buf[16] = {97, 97, 97, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
.global .align 1 .b8 _$_str3[32] = {115, 101, 116, 117, 112, 32, 102, 117, 110, 99, 116, 105, 111, 110, 44, 32, 99, 111, 110, 115, 116, 32, 100, 97, 116, 97, 61, 37, 108, 120, 10, 0};
.global .align 1 .b8 __const_$_bpf_main_$_msg[26] = {77, 101, 115, 115, 97, 103, 101, 32, 102, 114, 111, 109, 32, 98, 112, 102, 58, 32, 37, 100, 44, 32, 37, 108, 120, 0};
.global .align 1 .b8 _$_str4[11] = {99, 97, 108, 108, 32, 100, 111, 110, 101, 10, 0};
.global .align 1 .b8 _$_str5[23] = {103, 111, 116, 32, 114, 101, 115, 112, 111, 110, 115, 101, 32, 37, 100, 32, 97, 116, 32, 37, 100, 10, 0};
                                        // @spin_lock
.visible .func spin_lock(
	.param .b64 spin_lock_param_0
)
{
	.reg .pred 	%p<2>;
	.reg .b32 	%r<2>;
	.reg .b64 	%rd<2>;

// %bb.0:
	ld.param.u64 	%rd1, [spin_lock_param_0];
$L__BB0_1:                              // =>This Inner Loop Header: Depth=1
	atom.cas.b32 	%r1, [%rd1], 0, 1;
	setp.eq.s32 	%p1, %r1, 1;
	@%p1 bra 	$L__BB0_1;
// %bb.2:
	ret;
                                        // -- End function
}
	// .globl	spin_unlock             // -- Begin function spin_unlock
.visible .func spin_unlock(
	.param .b64 spin_unlock_param_0
)                                       // @spin_unlock
{
	.reg .b32 	%r<2>;
	.reg .b64 	%rd<2>;

// %bb.0:
	ld.param.u64 	%rd1, [spin_unlock_param_0];
	atom.exch.b32 	%r1, [%rd1], 0;
	ret;
                                        // -- End function
}
	// .globl	make_helper_call        // -- Begin function make_helper_call
.visible .func  (.param .align 8 .b8 func_retval0[8]) make_helper_call(
	.param .b64 make_helper_call_param_0,
	.param .b32 make_helper_call_param_1
)                                       // @make_helper_call
{
	.reg .pred 	%p<7>;
	.reg .b32 	%r<15>;
	.reg .b64 	%rd<14>;

// %bb.0:
	ld.param.u32 	%r5, [make_helper_call_param_1];
	ld.param.u64 	%rd6, [make_helper_call_param_0];
	ld.const.u64 	%rd1, [constData];
	mov.u32 	%r7, %tid.x;
	and.b32  	%r1, %r7, 31;
	add.s64 	%rd10, %rd1, 4;
	mov.u32 	%r14, 0;
	mov.u64 	%rd13, 0;
	add.s64 	%rd8, %rd1, 8;
	mov.u32 	%r12, 42;
	bra.uni 	$L__BB2_1;
$L__BB2_4:                              //   in Loop: Header=BB2_1 Depth=1
	bar.warp.sync 	%r3;
	add.s32 	%r14, %r14, 1;
	setp.eq.s32 	%p6, %r14, 32;
	@%p6 bra 	$L__BB2_5;
$L__BB2_1:                              // =>This Loop Header: Depth=1
                                        //     Child Loop BB2_2 Depth 2
	// begin inline asm
	activemask.b32 %r3;
	// end inline asm
	shr.u32 	%r9, %r3, %r14;
	and.b32  	%r10, %r9, 1;
	setp.eq.b32 	%p1, %r10, 1;
	not.pred 	%p2, %p1;
	setp.ne.s32 	%p3, %r1, %r14;
	or.pred  	%p4, %p3, %p2;
	@%p4 bra 	$L__BB2_4;
$L__BB2_2:                              //   Parent Loop BB2_1 Depth=1
                                        // =>  This Inner Loop Header: Depth=2
	atom.cas.b32 	%r11, [%rd8], 0, 1;
	setp.eq.s32 	%p5, %r11, 1;
	@%p5 bra 	$L__BB2_2;
// %bb.3:                               //   in Loop: Header=BB2_1 Depth=1
	st.u32 	[%rd1+12], %r5;
	st.u64 	[%rd1+16], %rd6;
	// begin inline asm
	.reg .pred p0;                   
	membar.sys;                      
	st.global.u32 [%rd1], 1;           
	spin_wait:                       
	membar.sys;                      
	ld.global.u32 %r12, [%rd10];          
	setp.eq.u32 p0, %r12, 0;           
	@p0 bra spin_wait;               
	st.global.u32 [%rd10], 0;           
	membar.sys;                      
	
	// end inline asm
	ld.u64 	%rd13, [%rd1+2147483680];
	atom.exch.b32 	%r13, [%rd8], 0;
	bra.uni 	$L__BB2_4;
$L__BB2_5:
	st.param.b64 	[func_retval0+0], %rd13;
	ret;
                                        // -- End function
}
	// .globl	_Z17getGlobalThreadIdv  // -- Begin function _Z17getGlobalThreadIdv
.visible .func  (.param .b64 func_retval0) _Z17getGlobalThreadIdv() // @_Z17getGlobalThreadIdv
{
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<8>;

// %bb.0:
	mov.u32 	%r1, %ctaid.x;
	mov.u32 	%r2, %ntid.x;
	mov.u32 	%r3, %tid.x;
	mad.lo.s32 	%r4, %r1, %r2, %r3;
	mov.u32 	%r5, %ctaid.y;
	mov.u32 	%r6, %ntid.y;
	mov.u32 	%r7, %tid.y;
	mad.lo.s32 	%r8, %r5, %r6, %r7;
	mov.u32 	%r9, %ctaid.z;
	mov.u32 	%r10, %ntid.z;
	mov.u32 	%r11, %tid.z;
	mad.lo.s32 	%r12, %r9, %r10, %r11;
	mov.u32 	%r13, %nctaid.x;
	mul.lo.s32 	%r14, %r13, %r2;
	mov.u32 	%r15, %nctaid.y;
	mul.lo.s32 	%r16, %r15, %r6;
	cvt.s64.s32 	%rd1, %r12;
	mul.wide.s32 	%rd2, %r16, %r14;
	mul.lo.s64 	%rd3, %rd2, %rd1;
	mul.lo.s32 	%r17, %r8, %r14;
	cvt.s64.s32 	%rd4, %r17;
	cvt.s64.s32 	%rd5, %r4;
	add.s64 	%rd6, %rd4, %rd5;
	add.s64 	%rd7, %rd6, %rd3;
	st.param.b64 	[func_retval0+0], %rd7;
	ret;
                                        // -- End function
}
	// .globl	_Z16array_map_offsetmRK12MapBasicInfom // -- Begin function _Z16array_map_offsetmRK12MapBasicInfom
.visible .func  (.param .b64 func_retval0) _Z16array_map_offsetmRK12MapBasicInfom(
	.param .b64 _Z16array_map_offsetmRK12MapBasicInfom_param_0,
	.param .b64 _Z16array_map_offsetmRK12MapBasicInfom_param_1,
	.param .b64 _Z16array_map_offsetmRK12MapBasicInfom_param_2
)                                       // @_Z16array_map_offsetmRK12MapBasicInfom
{
	.local .align 8 .b8 	__local_depot4[24];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<2>;
	.reg .b32 	%r<20>;
	.reg .b64 	%rd<26>;

// %bb.0:
	mov.u64 	%SPL, __local_depot4;
	cvta.local.u64 	%SP, %SPL;
	ld.param.u64 	%rd7, [_Z16array_map_offsetmRK12MapBasicInfom_param_1];
	ld.param.u64 	%rd6, [_Z16array_map_offsetmRK12MapBasicInfom_param_0];
	ld.u64 	%rd25, [%rd7+32];
	mov.u32 	%r1, %ctaid.x;
	mov.u32 	%r2, %ntid.x;
	mov.u32 	%r3, %tid.x;
	mad.lo.s32 	%r4, %r1, %r2, %r3;
	mov.u32 	%r5, %ctaid.y;
	mov.u32 	%r6, %ntid.y;
	mov.u32 	%r7, %tid.y;
	mad.lo.s32 	%r8, %r5, %r6, %r7;
	mov.u32 	%r9, %ctaid.z;
	mov.u32 	%r10, %ntid.z;
	mov.u32 	%r11, %tid.z;
	mad.lo.s32 	%r12, %r9, %r10, %r11;
	mov.u32 	%r13, %nctaid.x;
	mul.lo.s32 	%r14, %r13, %r2;
	mov.u32 	%r15, %nctaid.y;
	mul.lo.s32 	%r16, %r15, %r6;
	cvt.s64.s32 	%rd10, %r12;
	mul.wide.s32 	%rd11, %r16, %r14;
	mul.lo.s64 	%rd12, %rd11, %rd10;
	mul.lo.s32 	%r17, %r8, %r14;
	cvt.s64.s32 	%rd13, %r17;
	cvt.s64.s32 	%rd14, %r4;
	add.s64 	%rd15, %rd13, %rd14;
	add.s64 	%rd3, %rd15, %rd12;
	setp.gt.u64 	%p1, %rd25, %rd3;
	@%p1 bra 	$L__BB4_2;
// %bb.1:
	ld.param.u64 	%rd8, [_Z16array_map_offsetmRK12MapBasicInfom_param_2];
	add.u64 	%rd9, %SP, 0;
	add.u64 	%rd1, %SPL, 0;
	st.local.u64 	[%rd1], %rd3;
	st.local.u64 	[%rd1+8], %rd25;
	st.local.u64 	[%rd1+16], %rd8;
	mov.u64 	%rd16, _$_str;
	cvta.global.u64 	%rd17, %rd16;
	{ // callseq 0, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd17;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd9;
	.param .b32 retval0;
	call.uni (retval0), 
	vprintf, 
	(
	param0, 
	param1
	);
	ld.param.b32 	%r18, [retval0+0];
	} // callseq 0
	ld.u64 	%rd25, [%rd7+32];
$L__BB4_2:
	ld.u64 	%rd19, [%rd7+24];
	ld.s32 	%rd20, [%rd7+8];
	mul.lo.s64 	%rd21, %rd25, %rd6;
	add.s64 	%rd22, %rd21, %rd3;
	mul.lo.s64 	%rd23, %rd22, %rd20;
	add.s64 	%rd24, %rd23, %rd19;
	st.param.b64 	[func_retval0+0], %rd24;
	ret;
                                        // -- End function
}
	// .globl	_bpf_helper_ext_0001    // -- Begin function _bpf_helper_ext_0001
.visible .func  (.param .b64 func_retval0) _bpf_helper_ext_0001(
	.param .b64 _bpf_helper_ext_0001_param_0,
	.param .b64 _bpf_helper_ext_0001_param_1,
	.param .b64 _bpf_helper_ext_0001_param_2,
	.param .b64 _bpf_helper_ext_0001_param_3,
	.param .b64 _bpf_helper_ext_0001_param_4
)                                       // @_bpf_helper_ext_0001
{
	.local .align 8 .b8 	__local_depot5[24];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<15>;
	.reg .b16 	%rs<6>;
	.reg .b32 	%r<47>;
	.reg .b64 	%rd<78>;

// %bb.0:
	mov.u64 	%SPL, __local_depot5;
	cvta.local.u64 	%SP, %SPL;
	ld.param.u64 	%rd26, [_bpf_helper_ext_0001_param_1];
	ld.param.u64 	%rd25, [_bpf_helper_ext_0001_param_0];
	mul.lo.s64 	%rd28, %rd25, 40;
	mov.u64 	%rd29, map_info;
	add.s64 	%rd30, %rd29, %rd28;
	ld.const.u32 	%r10, [%rd30+16];
	setp.eq.s32 	%p1, %r10, 1503;
	@%p1 bra 	$L__BB5_5;
// %bb.1:
	setp.ne.s32 	%p2, %r10, 1502;
	@%p2 bra 	$L__BB5_6;
// %bb.2:
	ld.u32 	%rd4, [%rd26];
	ld.const.u64 	%rd5, [%rd30+32];
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %ntid.x;
	mov.u32 	%r13, %tid.x;
	mad.lo.s32 	%r14, %r11, %r12, %r13;
	mov.u32 	%r15, %ctaid.y;
	mov.u32 	%r16, %ntid.y;
	mov.u32 	%r17, %tid.y;
	mad.lo.s32 	%r18, %r15, %r16, %r17;
	mov.u32 	%r19, %ctaid.z;
	mov.u32 	%r20, %ntid.z;
	mov.u32 	%r21, %tid.z;
	mad.lo.s32 	%r22, %r19, %r20, %r21;
	mov.u32 	%r23, %nctaid.x;
	mul.lo.s32 	%r24, %r23, %r12;
	mov.u32 	%r25, %nctaid.y;
	mul.lo.s32 	%r26, %r25, %r16;
	cvt.s64.s32 	%rd41, %r22;
	mul.wide.s32 	%rd42, %r26, %r24;
	mul.lo.s64 	%rd43, %rd42, %rd41;
	mul.lo.s32 	%r27, %r18, %r24;
	cvt.s64.s32 	%rd44, %r27;
	cvt.s64.s32 	%rd45, %r14;
	add.s64 	%rd46, %rd44, %rd45;
	add.s64 	%rd6, %rd46, %rd43;
	setp.gt.u64 	%p3, %rd5, %rd6;
	@%p3 bra 	$L__BB5_4;
// %bb.3:
	add.u64 	%rd27, %SP, 0;
	add.u64 	%rd1, %SPL, 0;
	st.local.u64 	[%rd1], %rd6;
	st.local.u64 	[%rd1+8], %rd5;
	st.local.u64 	[%rd1+16], %rd25;
	mov.u64 	%rd47, _$_str;
	cvta.global.u64 	%rd48, %rd47;
	{ // callseq 1, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd48;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd27;
	.param .b32 retval0;
	call.uni (retval0), 
	vprintf, 
	(
	param0, 
	param1
	);
	ld.param.b32 	%r28, [retval0+0];
	} // callseq 1
$L__BB5_4:
	ld.const.u64 	%rd53, [%rd30+24];
	ld.const.s32 	%rd54, [%rd30+8];
	mul.lo.s64 	%rd55, %rd5, %rd4;
	add.s64 	%rd56, %rd55, %rd6;
	mul.lo.s64 	%rd57, %rd56, %rd54;
	add.s64 	%rd77, %rd57, %rd53;
	bra.uni 	$L__BB5_18;
$L__BB5_5:
	ld.u32 	%rd31, [%rd26];
	ld.const.u64 	%rd35, [%rd30+24];
	ld.const.s32 	%rd36, [%rd30+8];
	mul.lo.s64 	%rd37, %rd36, %rd31;
	add.s64 	%rd77, %rd35, %rd37;
$L__BB5_18:
	st.param.b64 	[func_retval0+0], %rd77;
	ret;
$L__BB5_6:
	ld.const.u64 	%rd68, [constData];
	ld.const.u32 	%r30, [%rd30+4];
	setp.lt.s32 	%p4, %r30, 1;
	@%p4 bra 	$L__BB5_13;
// %bb.7:
	cvt.u64.u32 	%rd9, %r30;
	cvt.u32.u64 	%r32, %rd9;
	and.b32  	%r45, %r32, 3;
	setp.lt.u32 	%p5, %r32, 4;
	mov.u32 	%r44, 0;
	@%p5 bra 	$L__BB5_10;
// %bb.8:
	add.s64 	%rd3, %rd68, 24;
	and.b64  	%rd10, %rd9, 4294967292;
	add.s64 	%rd11, %rd26, 3;
	mov.u64 	%rd72, 0;
	cvt.u32.u64 	%r33, %rd10;
$L__BB5_9:                              // =>This Inner Loop Header: Depth=1
	add.s64 	%rd62, %rd11, %rd72;
	ld.u8 	%rs1, [%rd62+-3];
	add.s64 	%rd63, %rd3, %rd72;
	st.u8 	[%rd63], %rs1;
	ld.u8 	%rs2, [%rd62+-2];
	st.u8 	[%rd63+1], %rs2;
	ld.u8 	%rs3, [%rd62+-1];
	st.u8 	[%rd63+2], %rs3;
	ld.u8 	%rs4, [%rd62];
	st.u8 	[%rd63+3], %rs4;
	add.s64 	%rd72, %rd72, 4;
	cvt.u32.u64 	%r44, %rd72;
	setp.ne.s32 	%p6, %r33, %r44;
	@%p6 bra 	$L__BB5_9;
$L__BB5_10:
	setp.eq.s32 	%p7, %r45, 0;
	@%p7 bra 	$L__BB5_13;
// %bb.11:
	cvt.u64.u32 	%rd64, %r44;
	add.s64 	%rd65, %rd64, %rd68;
	add.s64 	%rd74, %rd65, 24;
	add.s64 	%rd73, %rd26, %rd64;
$L__BB5_12:                             // =>This Inner Loop Header: Depth=1
	.pragma "nounroll";
	ld.u8 	%rs5, [%rd73];
	st.u8 	[%rd74], %rs5;
	add.s64 	%rd74, %rd74, 1;
	add.s64 	%rd73, %rd73, 1;
	add.s32 	%r45, %r45, -1;
	setp.ne.s32 	%p8, %r45, 0;
	@%p8 bra 	$L__BB5_12;
$L__BB5_13:
	mov.u32 	%r46, 0;
	mov.u64 	%rd77, 0;
	mov.u32 	%r35, %tid.x;
	and.b32  	%r6, %r35, 31;
	add.s64 	%rd69, %rd68, 4;
	add.s64 	%rd67, %rd68, 8;
	mov.u32 	%r41, 1;
	mov.u32 	%r40, 42;
	bra.uni 	$L__BB5_14;
$L__BB5_17:                             //   in Loop: Header=BB5_14 Depth=1
	bar.warp.sync 	%r8;
	add.s32 	%r46, %r46, 1;
	setp.ne.s32 	%p14, %r46, 32;
	@%p14 bra 	$L__BB5_14;
	bra.uni 	$L__BB5_18;
$L__BB5_14:                             // =>This Loop Header: Depth=1
                                        //     Child Loop BB5_15 Depth 2
	// begin inline asm
	activemask.b32 %r8;
	// end inline asm
	shr.u32 	%r37, %r8, %r46;
	and.b32  	%r38, %r37, 1;
	setp.eq.b32 	%p9, %r38, 1;
	not.pred 	%p10, %p9;
	setp.ne.s32 	%p11, %r6, %r46;
	or.pred  	%p12, %p11, %p10;
	@%p12 bra 	$L__BB5_17;
$L__BB5_15:                             //   Parent Loop BB5_14 Depth=1
                                        // =>  This Inner Loop Header: Depth=2
	atom.cas.b32 	%r39, [%rd67], 0, 1;
	setp.eq.s32 	%p13, %r39, 1;
	@%p13 bra 	$L__BB5_15;
// %bb.16:                              //   in Loop: Header=BB5_14 Depth=1
	st.u32 	[%rd68+12], %r41;
	st.u64 	[%rd68+16], %rd25;
	// begin inline asm
	.reg .pred p0;                   
	membar.sys;                      
	st.global.u32 [%rd68], 1;           
	spin_wait:                       
	membar.sys;                      
	ld.global.u32 %r40, [%rd69];          
	setp.eq.u32 p0, %r40, 0;           
	@p0 bra spin_wait;               
	st.global.u32 [%rd69], 0;           
	membar.sys;                      
	
	// end inline asm
	ld.u64 	%rd77, [%rd68+2147483680];
	atom.exch.b32 	%r42, [%rd67], 0;
	bra.uni 	$L__BB5_17;
                                        // -- End function
}
	// .globl	_bpf_helper_ext_0002    // -- Begin function _bpf_helper_ext_0002
.visible .func  (.param .b64 func_retval0) _bpf_helper_ext_0002(
	.param .b64 _bpf_helper_ext_0002_param_0,
	.param .b64 _bpf_helper_ext_0002_param_1,
	.param .b64 _bpf_helper_ext_0002_param_2,
	.param .b64 _bpf_helper_ext_0002_param_3,
	.param .b64 _bpf_helper_ext_0002_param_4
)                                       // @_bpf_helper_ext_0002
{
	.local .align 8 .b8 	__local_depot6[24];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<30>;
	.reg .b16 	%rs<21>;
	.reg .b32 	%r<81>;
	.reg .b64 	%rd<146>;

// %bb.0:
	mov.u64 	%SPL, __local_depot6;
	cvta.local.u64 	%SP, %SPL;
	ld.param.u64 	%rd64, [_bpf_helper_ext_0002_param_2];
	ld.param.u64 	%rd63, [_bpf_helper_ext_0002_param_1];
	ld.param.u64 	%rd62, [_bpf_helper_ext_0002_param_0];
	mul.lo.s64 	%rd67, %rd62, 40;
	mov.u64 	%rd68, map_info;
	add.s64 	%rd69, %rd68, %rd67;
	ld.const.u32 	%r25, [%rd69+16];
	setp.eq.s32 	%p1, %r25, 1503;
	@%p1 bra 	$L__BB6_11;
// %bb.1:
	setp.ne.s32 	%p2, %r25, 1502;
	@%p2 bra 	$L__BB6_19;
// %bb.2:
	ld.u32 	%rd4, [%rd63];
	ld.const.u64 	%rd5, [%rd69+32];
	mov.u32 	%r30, %ctaid.x;
	mov.u32 	%r31, %ntid.x;
	mov.u32 	%r32, %tid.x;
	mad.lo.s32 	%r33, %r30, %r31, %r32;
	mov.u32 	%r34, %ctaid.y;
	mov.u32 	%r35, %ntid.y;
	mov.u32 	%r36, %tid.y;
	mad.lo.s32 	%r37, %r34, %r35, %r36;
	mov.u32 	%r38, %ctaid.z;
	mov.u32 	%r39, %ntid.z;
	mov.u32 	%r40, %tid.z;
	mad.lo.s32 	%r41, %r38, %r39, %r40;
	mov.u32 	%r42, %nctaid.x;
	mul.lo.s32 	%r43, %r42, %r31;
	mov.u32 	%r44, %nctaid.y;
	mul.lo.s32 	%r45, %r44, %r35;
	cvt.s64.s32 	%rd84, %r41;
	mul.wide.s32 	%rd85, %r45, %r43;
	mul.lo.s64 	%rd86, %rd85, %rd84;
	mul.lo.s32 	%r46, %r37, %r43;
	cvt.s64.s32 	%rd87, %r46;
	cvt.s64.s32 	%rd88, %r33;
	add.s64 	%rd89, %rd87, %rd88;
	add.s64 	%rd6, %rd89, %rd86;
	setp.gt.u64 	%p8, %rd5, %rd6;
	@%p8 bra 	$L__BB6_4;
// %bb.3:
	add.u64 	%rd66, %SP, 0;
	add.u64 	%rd1, %SPL, 0;
	st.local.u64 	[%rd1], %rd6;
	st.local.u64 	[%rd1+8], %rd5;
	st.local.u64 	[%rd1+16], %rd62;
	mov.u64 	%rd90, _$_str;
	cvta.global.u64 	%rd91, %rd90;
	{ // callseq 2, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd91;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd66;
	.param .b32 retval0;
	call.uni (retval0), 
	vprintf, 
	(
	param0, 
	param1
	);
	ld.param.b32 	%r47, [retval0+0];
	} // callseq 2
$L__BB6_4:
	ld.const.u32 	%r49, [%rd69+8];
	setp.lt.s32 	%p9, %r49, 1;
	mov.u64 	%rd145, 0;
	@%p9 bra 	$L__BB6_39;
// %bb.5:
	ld.const.u64 	%rd97, [%rd69+24];
	cvt.u64.u32 	%rd7, %r49;
	cvt.s64.s32 	%rd98, %r49;
	mul.lo.s64 	%rd99, %rd5, %rd4;
	add.s64 	%rd100, %rd99, %rd6;
	mul.lo.s64 	%rd101, %rd100, %rd98;
	add.s64 	%rd8, %rd101, %rd97;
	cvt.u32.u64 	%r51, %rd7;
	and.b32  	%r80, %r51, 3;
	setp.lt.u32 	%p10, %r51, 4;
	mov.u32 	%r79, 0;
	@%p10 bra 	$L__BB6_8;
// %bb.6:
	and.b64  	%rd9, %rd7, 4294967292;
	add.s64 	%rd10, %rd64, 3;
	mov.u64 	%rd131, 0;
	cvt.u32.u64 	%r52, %rd9;
$L__BB6_7:                              // =>This Inner Loop Header: Depth=1
	add.s64 	%rd103, %rd10, %rd131;
	ld.u8 	%rs6, [%rd103+-3];
	add.s64 	%rd104, %rd8, %rd131;
	st.u8 	[%rd104], %rs6;
	ld.u8 	%rs7, [%rd103+-2];
	st.u8 	[%rd104+1], %rs7;
	ld.u8 	%rs8, [%rd103+-1];
	st.u8 	[%rd104+2], %rs8;
	ld.u8 	%rs9, [%rd103];
	st.u8 	[%rd104+3], %rs9;
	add.s64 	%rd131, %rd131, 4;
	cvt.u32.u64 	%r79, %rd131;
	setp.eq.s32 	%p11, %r52, %r79;
	@%p11 bra 	$L__BB6_8;
	bra.uni 	$L__BB6_7;
$L__BB6_8:
	setp.eq.s32 	%p12, %r80, 0;
	@%p12 bra 	$L__BB6_39;
// %bb.9:
	cvt.u64.u32 	%rd106, %r79;
	add.s64 	%rd144, %rd8, %rd106;
	add.s64 	%rd143, %rd64, %rd106;
$L__BB6_10:                             // =>This Inner Loop Header: Depth=1
	.pragma "nounroll";
	ld.u8 	%rs10, [%rd143];
	st.u8 	[%rd144], %rs10;
	add.s64 	%rd144, %rd144, 1;
	add.s64 	%rd143, %rd143, 1;
	add.s32 	%r80, %r80, -1;
	setp.ne.s32 	%p13, %r80, 0;
	@%p13 bra 	$L__BB6_10;
	bra.uni 	$L__BB6_39;
$L__BB6_11:
	ld.const.u32 	%r26, [%rd69+8];
	setp.lt.s32 	%p3, %r26, 1;
	@%p3 bra 	$L__BB6_18;
// %bb.12:
	ld.u32 	%rd70, [%rd63];
	ld.const.u64 	%rd13, [%rd69+24];
	cvt.u64.u32 	%rd14, %r26;
	cvt.s64.s32 	%rd74, %r26;
	mul.lo.s64 	%rd15, %rd74, %rd70;
	cvt.u32.u64 	%r28, %rd14;
	and.b32  	%r73, %r28, 3;
	setp.lt.u32 	%p4, %r28, 4;
	mov.u32 	%r72, 0;
	@%p4 bra 	$L__BB6_15;
// %bb.13:
	add.s64 	%rd16, %rd13, %rd15;
	and.b64  	%rd17, %rd14, 4294967292;
	add.s64 	%rd18, %rd64, 3;
	mov.u64 	%rd132, 0;
	cvt.u32.u64 	%r29, %rd17;
$L__BB6_14:                             // =>This Inner Loop Header: Depth=1
	add.s64 	%rd76, %rd18, %rd132;
	ld.u8 	%rs1, [%rd76+-3];
	add.s64 	%rd77, %rd16, %rd132;
	st.u8 	[%rd77], %rs1;
	ld.u8 	%rs2, [%rd76+-2];
	st.u8 	[%rd77+1], %rs2;
	ld.u8 	%rs3, [%rd76+-1];
	st.u8 	[%rd77+2], %rs3;
	ld.u8 	%rs4, [%rd76];
	st.u8 	[%rd77+3], %rs4;
	add.s64 	%rd132, %rd132, 4;
	cvt.u32.u64 	%r72, %rd132;
	setp.ne.s32 	%p5, %r29, %r72;
	@%p5 bra 	$L__BB6_14;
$L__BB6_15:
	setp.eq.s32 	%p6, %r73, 0;
	@%p6 bra 	$L__BB6_18;
// %bb.16:
	cvt.u64.u32 	%rd78, %r72;
	add.s64 	%rd79, %rd15, %rd78;
	add.s64 	%rd134, %rd13, %rd79;
	add.s64 	%rd133, %rd64, %rd78;
$L__BB6_17:                             // =>This Inner Loop Header: Depth=1
	.pragma "nounroll";
	ld.u8 	%rs5, [%rd133];
	st.u8 	[%rd134], %rs5;
	add.s64 	%rd134, %rd134, 1;
	add.s64 	%rd133, %rd133, 1;
	add.s32 	%r73, %r73, -1;
	setp.ne.s32 	%p7, %r73, 0;
	@%p7 bra 	$L__BB6_17;
$L__BB6_18:
	// begin inline asm
	membar.sys;                      
	
	// end inline asm
	mov.u64 	%rd145, 0;
	bra.uni 	$L__BB6_39;
$L__BB6_19:
	ld.const.u64 	%rd126, [constData];
	ld.const.u32 	%r53, [%rd69+4];
	setp.lt.s32 	%p14, %r53, 1;
	@%p14 bra 	$L__BB6_26;
// %bb.20:
	cvt.u64.u32 	%rd27, %r53;
	cvt.u32.u64 	%r55, %rd27;
	and.b32  	%r75, %r55, 3;
	setp.lt.u32 	%p15, %r55, 4;
	mov.u32 	%r74, 0;
	@%p15 bra 	$L__BB6_23;
// %bb.21:
	add.s64 	%rd3, %rd126, 24;
	and.b64  	%rd28, %rd27, 4294967292;
	add.s64 	%rd29, %rd63, 3;
	mov.u64 	%rd135, 0;
	cvt.u32.u64 	%r56, %rd28;
$L__BB6_22:                             // =>This Inner Loop Header: Depth=1
	add.s64 	%rd112, %rd29, %rd135;
	ld.u8 	%rs11, [%rd112+-3];
	add.s64 	%rd113, %rd3, %rd135;
	st.u8 	[%rd113], %rs11;
	ld.u8 	%rs12, [%rd112+-2];
	st.u8 	[%rd113+1], %rs12;
	ld.u8 	%rs13, [%rd112+-1];
	st.u8 	[%rd113+2], %rs13;
	ld.u8 	%rs14, [%rd112];
	st.u8 	[%rd113+3], %rs14;
	add.s64 	%rd135, %rd135, 4;
	cvt.u32.u64 	%r74, %rd135;
	setp.ne.s32 	%p16, %r56, %r74;
	@%p16 bra 	$L__BB6_22;
$L__BB6_23:
	setp.eq.s32 	%p17, %r75, 0;
	@%p17 bra 	$L__BB6_26;
// %bb.24:
	cvt.u64.u32 	%rd114, %r74;
	add.s64 	%rd115, %rd114, %rd126;
	add.s64 	%rd137, %rd115, 24;
	add.s64 	%rd136, %rd63, %rd114;
$L__BB6_25:                             // =>This Inner Loop Header: Depth=1
	.pragma "nounroll";
	ld.u8 	%rs15, [%rd136];
	st.u8 	[%rd137], %rs15;
	add.s64 	%rd137, %rd137, 1;
	add.s64 	%rd136, %rd136, 1;
	add.s32 	%r75, %r75, -1;
	setp.ne.s32 	%p18, %r75, 0;
	@%p18 bra 	$L__BB6_25;
$L__BB6_26:
	ld.param.u64 	%rd65, [_bpf_helper_ext_0002_param_3];
	ld.const.u32 	%r57, [%rd69+8];
	setp.lt.s32 	%p19, %r57, 1;
	@%p19 bra 	$L__BB6_33;
// %bb.27:
	cvt.u64.u32 	%rd39, %r57;
	cvt.u32.u64 	%r59, %rd39;
	and.b32  	%r77, %r59, 3;
	setp.lt.u32 	%p20, %r59, 4;
	mov.u32 	%r76, 0;
	@%p20 bra 	$L__BB6_30;
// %bb.28:
	add.s64 	%rd38, %rd126, 1073741848;
	and.b64  	%rd40, %rd39, 4294967292;
	add.s64 	%rd41, %rd64, 3;
	mov.u64 	%rd138, 0;
	cvt.u32.u64 	%r60, %rd40;
$L__BB6_29:                             // =>This Inner Loop Header: Depth=1
	add.s64 	%rd120, %rd41, %rd138;
	ld.u8 	%rs16, [%rd120+-3];
	add.s64 	%rd121, %rd38, %rd138;
	st.u8 	[%rd121], %rs16;
	ld.u8 	%rs17, [%rd120+-2];
	st.u8 	[%rd121+1], %rs17;
	ld.u8 	%rs18, [%rd120+-1];
	st.u8 	[%rd121+2], %rs18;
	ld.u8 	%rs19, [%rd120];
	st.u8 	[%rd121+3], %rs19;
	add.s64 	%rd138, %rd138, 4;
	cvt.u32.u64 	%r76, %rd138;
	setp.ne.s32 	%p21, %r60, %r76;
	@%p21 bra 	$L__BB6_29;
$L__BB6_30:
	setp.eq.s32 	%p22, %r77, 0;
	@%p22 bra 	$L__BB6_33;
// %bb.31:
	cvt.u64.u32 	%rd122, %r76;
	add.s64 	%rd123, %rd122, %rd126;
	add.s64 	%rd140, %rd123, 1073741848;
	add.s64 	%rd139, %rd64, %rd122;
$L__BB6_32:                             // =>This Inner Loop Header: Depth=1
	.pragma "nounroll";
	ld.u8 	%rs20, [%rd139];
	st.u8 	[%rd140], %rs20;
	add.s64 	%rd140, %rd140, 1;
	add.s64 	%rd139, %rd139, 1;
	add.s32 	%r77, %r77, -1;
	setp.ne.s32 	%p23, %r77, 0;
	@%p23 bra 	$L__BB6_32;
$L__BB6_33:
	mov.u32 	%r78, 0;
	mov.u64 	%rd142, 0;
	st.u64 	[%rd126+2147483672], %rd65;
	mov.u32 	%r62, %tid.x;
	and.b32  	%r18, %r62, 31;
	add.s64 	%rd127, %rd126, 4;
	add.s64 	%rd125, %rd126, 8;
	mov.u32 	%r68, 2;
	mov.u32 	%r67, 42;
	bra.uni 	$L__BB6_34;
$L__BB6_37:                             //   in Loop: Header=BB6_34 Depth=1
	bar.warp.sync 	%r20;
	add.s32 	%r78, %r78, 1;
	setp.ne.s32 	%p29, %r78, 32;
	@%p29 bra 	$L__BB6_34;
	bra.uni 	$L__BB6_38;
$L__BB6_34:                             // =>This Loop Header: Depth=1
                                        //     Child Loop BB6_35 Depth 2
	// begin inline asm
	activemask.b32 %r20;
	// end inline asm
	shr.u32 	%r64, %r20, %r78;
	and.b32  	%r65, %r64, 1;
	setp.eq.b32 	%p24, %r65, 1;
	not.pred 	%p25, %p24;
	setp.ne.s32 	%p26, %r18, %r78;
	or.pred  	%p27, %p26, %p25;
	@%p27 bra 	$L__BB6_37;
$L__BB6_35:                             //   Parent Loop BB6_34 Depth=1
                                        // =>  This Inner Loop Header: Depth=2
	atom.cas.b32 	%r66, [%rd125], 0, 1;
	setp.eq.s32 	%p28, %r66, 1;
	@%p28 bra 	$L__BB6_35;
// %bb.36:                              //   in Loop: Header=BB6_34 Depth=1
	st.u32 	[%rd126+12], %r68;
	st.u64 	[%rd126+16], %rd62;
	// begin inline asm
	.reg .pred p0;                   
	membar.sys;                      
	st.global.u32 [%rd126], 1;           
	spin_wait:                       
	membar.sys;                      
	ld.global.u32 %r67, [%rd127];          
	setp.eq.u32 p0, %r67, 0;           
	@p0 bra spin_wait;               
	st.global.u32 [%rd127], 0;           
	membar.sys;                      
	
	// end inline asm
	ld.u64 	%rd142, [%rd126+2147483680];
	atom.exch.b32 	%r69, [%rd125], 0;
	bra.uni 	$L__BB6_37;
$L__BB6_38:
	cvt.s64.s32 	%rd145, %rd142;
$L__BB6_39:
	st.param.b64 	[func_retval0+0], %rd145;
	ret;
                                        // -- End function
}
	// .globl	_bpf_helper_ext_0003    // -- Begin function _bpf_helper_ext_0003
.visible .func  (.param .b64 func_retval0) _bpf_helper_ext_0003(
	.param .b64 _bpf_helper_ext_0003_param_0,
	.param .b64 _bpf_helper_ext_0003_param_1,
	.param .b64 _bpf_helper_ext_0003_param_2,
	.param .b64 _bpf_helper_ext_0003_param_3,
	.param .b64 _bpf_helper_ext_0003_param_4
)                                       // @_bpf_helper_ext_0003
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<6>;
	.reg .b32 	%r<27>;
	.reg .b64 	%rd<40>;

// %bb.0:
	ld.param.u64 	%rd18, [_bpf_helper_ext_0003_param_0];
	ld.const.u64 	%rd30, [constData];
	mul.lo.s64 	%rd20, %rd18, 40;
	mov.u64 	%rd21, map_info;
	add.s64 	%rd22, %rd21, %rd20;
	ld.const.u32 	%r10, [%rd22+4];
	setp.lt.s32 	%p1, %r10, 1;
	@%p1 bra 	$L__BB7_7;
// %bb.1:
	ld.param.u64 	%rd19, [_bpf_helper_ext_0003_param_1];
	cvt.u64.u32 	%rd3, %r10;
	cvt.u32.u64 	%r12, %rd3;
	and.b32  	%r25, %r12, 3;
	setp.lt.u32 	%p2, %r12, 4;
	mov.u32 	%r24, 0;
	@%p2 bra 	$L__BB7_4;
// %bb.2:
	add.s64 	%rd2, %rd30, 24;
	and.b64  	%rd4, %rd3, 4294967292;
	add.s64 	%rd5, %rd19, 3;
	mov.u64 	%rd35, 0;
	cvt.u32.u64 	%r13, %rd4;
$L__BB7_3:                              // =>This Inner Loop Header: Depth=1
	add.s64 	%rd24, %rd5, %rd35;
	ld.u8 	%rs1, [%rd24+-3];
	add.s64 	%rd25, %rd2, %rd35;
	st.u8 	[%rd25], %rs1;
	ld.u8 	%rs2, [%rd24+-2];
	st.u8 	[%rd25+1], %rs2;
	ld.u8 	%rs3, [%rd24+-1];
	st.u8 	[%rd25+2], %rs3;
	ld.u8 	%rs4, [%rd24];
	st.u8 	[%rd25+3], %rs4;
	add.s64 	%rd35, %rd35, 4;
	cvt.u32.u64 	%r24, %rd35;
	setp.ne.s32 	%p3, %r13, %r24;
	@%p3 bra 	$L__BB7_3;
$L__BB7_4:
	setp.eq.s32 	%p4, %r25, 0;
	@%p4 bra 	$L__BB7_7;
// %bb.5:
	cvt.u64.u32 	%rd26, %r24;
	add.s64 	%rd27, %rd26, %rd30;
	add.s64 	%rd37, %rd27, 24;
	add.s64 	%rd36, %rd19, %rd26;
$L__BB7_6:                              // =>This Inner Loop Header: Depth=1
	.pragma "nounroll";
	ld.u8 	%rs5, [%rd36];
	st.u8 	[%rd37], %rs5;
	add.s64 	%rd37, %rd37, 1;
	add.s64 	%rd36, %rd36, 1;
	add.s32 	%r25, %r25, -1;
	setp.ne.s32 	%p5, %r25, 0;
	@%p5 bra 	$L__BB7_6;
$L__BB7_7:
	mov.u32 	%r26, 0;
	mov.u64 	%rd39, 0;
	mov.u32 	%r15, %tid.x;
	and.b32  	%r6, %r15, 31;
	add.s64 	%rd31, %rd30, 4;
	add.s64 	%rd29, %rd30, 8;
	mov.u32 	%r21, 3;
	mov.u32 	%r20, 42;
	bra.uni 	$L__BB7_8;
$L__BB7_11:                             //   in Loop: Header=BB7_8 Depth=1
	bar.warp.sync 	%r8;
	add.s32 	%r26, %r26, 1;
	setp.ne.s32 	%p11, %r26, 32;
	@%p11 bra 	$L__BB7_8;
	bra.uni 	$L__BB7_12;
$L__BB7_8:                              // =>This Loop Header: Depth=1
                                        //     Child Loop BB7_9 Depth 2
	// begin inline asm
	activemask.b32 %r8;
	// end inline asm
	shr.u32 	%r17, %r8, %r26;
	and.b32  	%r18, %r17, 1;
	setp.eq.b32 	%p6, %r18, 1;
	not.pred 	%p7, %p6;
	setp.ne.s32 	%p8, %r6, %r26;
	or.pred  	%p9, %p8, %p7;
	@%p9 bra 	$L__BB7_11;
$L__BB7_9:                              //   Parent Loop BB7_8 Depth=1
                                        // =>  This Inner Loop Header: Depth=2
	atom.cas.b32 	%r19, [%rd29], 0, 1;
	setp.eq.s32 	%p10, %r19, 1;
	@%p10 bra 	$L__BB7_9;
// %bb.10:                              //   in Loop: Header=BB7_8 Depth=1
	st.u32 	[%rd30+12], %r21;
	st.u64 	[%rd30+16], %rd18;
	// begin inline asm
	.reg .pred p0;                   
	membar.sys;                      
	st.global.u32 [%rd30], 1;           
	spin_wait:                       
	membar.sys;                      
	ld.global.u32 %r20, [%rd31];          
	setp.eq.u32 p0, %r20, 0;           
	@p0 bra spin_wait;               
	st.global.u32 [%rd31], 0;           
	membar.sys;                      
	
	// end inline asm
	ld.u64 	%rd39, [%rd30+2147483680];
	atom.exch.b32 	%r22, [%rd29], 0;
	bra.uni 	$L__BB7_11;
$L__BB7_12:
	cvt.s64.s32 	%rd33, %rd39;
	st.param.b64 	[func_retval0+0], %rd33;
	ret;
                                        // -- End function
}
	// .globl	_bpf_helper_ext_0006    // -- Begin function _bpf_helper_ext_0006
.visible .func  (.param .b64 func_retval0) _bpf_helper_ext_0006(
	.param .b64 _bpf_helper_ext_0006_param_0,
	.param .b64 _bpf_helper_ext_0006_param_1,
	.param .b64 _bpf_helper_ext_0006_param_2,
	.param .b64 _bpf_helper_ext_0006_param_3,
	.param .b64 _bpf_helper_ext_0006_param_4
)                                       // @_bpf_helper_ext_0006
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<2>;
	.reg .b32 	%r<15>;
	.reg .b64 	%rd<29>;

// %bb.0:
	ld.param.u64 	%rd13, [_bpf_helper_ext_0006_param_4];
	ld.param.u64 	%rd12, [_bpf_helper_ext_0006_param_3];
	ld.param.u64 	%rd11, [_bpf_helper_ext_0006_param_2];
	ld.param.u64 	%rd10, [_bpf_helper_ext_0006_param_1];
	ld.const.u64 	%rd1, [constData];
	setp.eq.s64 	%p1, %rd10, 0;
	@%p1 bra 	$L__BB8_3;
// %bb.1:
	ld.param.u64 	%rd9, [_bpf_helper_ext_0006_param_0];
	add.s64 	%rd2, %rd1, 24;
	mov.u64 	%rd28, 0;
$L__BB8_2:                              // =>This Inner Loop Header: Depth=1
	add.s64 	%rd15, %rd9, %rd28;
	ld.u8 	%rs1, [%rd15];
	add.s64 	%rd16, %rd2, %rd28;
	st.u8 	[%rd16], %rs1;
	add.s64 	%rd17, %rd28, 1;
	and.b64  	%rd28, %rd17, 4294967295;
	setp.lt.u64 	%p2, %rd28, %rd10;
	@%p2 bra 	$L__BB8_2;
$L__BB8_3:
	st.u32 	[%rd1+1024], %rd10;
	st.u64 	[%rd1+1032], %rd11;
	st.u64 	[%rd1+1040], %rd12;
	st.u64 	[%rd1+1048], %rd13;
	mov.u32 	%r6, %tid.x;
	and.b32  	%r1, %r6, 31;
	add.s64 	%rd21, %rd1, 4;
	mov.u32 	%r14, 0;
	mov.u64 	%rd27, 0;
	add.s64 	%rd19, %rd1, 8;
	mov.u32 	%r12, 6;
	mov.u32 	%r11, 42;
	bra.uni 	$L__BB8_4;
$L__BB8_7:                              //   in Loop: Header=BB8_4 Depth=1
	bar.warp.sync 	%r3;
	add.s32 	%r14, %r14, 1;
	setp.ne.s32 	%p8, %r14, 32;
	@%p8 bra 	$L__BB8_4;
	bra.uni 	$L__BB8_8;
$L__BB8_4:                              // =>This Loop Header: Depth=1
                                        //     Child Loop BB8_5 Depth 2
	// begin inline asm
	activemask.b32 %r3;
	// end inline asm
	shr.u32 	%r8, %r3, %r14;
	and.b32  	%r9, %r8, 1;
	setp.eq.b32 	%p3, %r9, 1;
	not.pred 	%p4, %p3;
	setp.ne.s32 	%p5, %r1, %r14;
	or.pred  	%p6, %p5, %p4;
	@%p6 bra 	$L__BB8_7;
$L__BB8_5:                              //   Parent Loop BB8_4 Depth=1
                                        // =>  This Inner Loop Header: Depth=2
	atom.cas.b32 	%r10, [%rd19], 0, 1;
	setp.eq.s32 	%p7, %r10, 1;
	@%p7 bra 	$L__BB8_5;
// %bb.6:                               //   in Loop: Header=BB8_4 Depth=1
	st.u32 	[%rd1+12], %r12;
	mov.u64 	%rd22, 0;
	st.u64 	[%rd1+16], %rd22;
	// begin inline asm
	.reg .pred p0;                   
	membar.sys;                      
	st.global.u32 [%rd1], 1;           
	spin_wait:                       
	membar.sys;                      
	ld.global.u32 %r11, [%rd21];          
	setp.eq.u32 p0, %r11, 0;           
	@p0 bra spin_wait;               
	st.global.u32 [%rd21], 0;           
	membar.sys;                      
	
	// end inline asm
	ld.u64 	%rd27, [%rd1+2147483680];
	atom.exch.b32 	%r13, [%rd19], 0;
	bra.uni 	$L__BB8_7;
$L__BB8_8:
	cvt.s64.s32 	%rd24, %rd27;
	st.param.b64 	[func_retval0+0], %rd24;
	ret;
                                        // -- End function
}
	// .globl	_bpf_helper_ext_0014    // -- Begin function _bpf_helper_ext_0014
.visible .func  (.param .b64 func_retval0) _bpf_helper_ext_0014(
	.param .b64 _bpf_helper_ext_0014_param_0,
	.param .b64 _bpf_helper_ext_0014_param_1,
	.param .b64 _bpf_helper_ext_0014_param_2,
	.param .b64 _bpf_helper_ext_0014_param_3,
	.param .b64 _bpf_helper_ext_0014_param_4
)                                       // @_bpf_helper_ext_0014
{
	.reg .pred 	%p<7>;
	.reg .b32 	%r<15>;
	.reg .b64 	%rd<14>;

// %bb.0:
	ld.const.u64 	%rd8, [constData];
	mov.u32 	%r6, %tid.x;
	and.b32  	%r1, %r6, 31;
	add.s64 	%rd9, %rd8, 4;
	mov.u32 	%r14, 0;
	mov.u64 	%rd6, 0;
	add.s64 	%rd7, %rd8, 8;
	mov.u32 	%r12, 14;
	mov.u32 	%r11, 42;
	mov.u64 	%rd13, %rd6;
	bra.uni 	$L__BB9_1;
$L__BB9_4:                              //   in Loop: Header=BB9_1 Depth=1
	bar.warp.sync 	%r3;
	add.s32 	%r14, %r14, 1;
	setp.ne.s32 	%p6, %r14, 32;
	@%p6 bra 	$L__BB9_1;
	bra.uni 	$L__BB9_5;
$L__BB9_1:                              // =>This Loop Header: Depth=1
                                        //     Child Loop BB9_2 Depth 2
	// begin inline asm
	activemask.b32 %r3;
	// end inline asm
	shr.u32 	%r8, %r3, %r14;
	and.b32  	%r9, %r8, 1;
	setp.eq.b32 	%p1, %r9, 1;
	not.pred 	%p2, %p1;
	setp.ne.s32 	%p3, %r1, %r14;
	or.pred  	%p4, %p3, %p2;
	@%p4 bra 	$L__BB9_4;
$L__BB9_2:                              //   Parent Loop BB9_1 Depth=1
                                        // =>  This Inner Loop Header: Depth=2
	atom.cas.b32 	%r10, [%rd7], 0, 1;
	setp.eq.s32 	%p5, %r10, 1;
	@%p5 bra 	$L__BB9_2;
// %bb.3:                               //   in Loop: Header=BB9_1 Depth=1
	st.u32 	[%rd8+12], %r12;
	st.u64 	[%rd8+16], %rd6;
	// begin inline asm
	.reg .pred p0;                   
	membar.sys;                      
	st.global.u32 [%rd8], 1;           
	spin_wait:                       
	membar.sys;                      
	ld.global.u32 %r11, [%rd9];          
	setp.eq.u32 p0, %r11, 0;           
	@p0 bra spin_wait;               
	st.global.u32 [%rd9], 0;           
	membar.sys;                      
	
	// end inline asm
	ld.u64 	%rd13, [%rd8+2147483680];
	atom.exch.b32 	%r13, [%rd7], 0;
	bra.uni 	$L__BB9_4;
$L__BB9_5:
	st.param.b64 	[func_retval0+0], %rd13;
	ret;
                                        // -- End function
}
	// .globl	_bpf_helper_ext_0025    // -- Begin function _bpf_helper_ext_0025
.visible .func  (.param .b64 func_retval0) _bpf_helper_ext_0025(
	.param .b64 _bpf_helper_ext_0025_param_0,
	.param .b64 _bpf_helper_ext_0025_param_1,
	.param .b64 _bpf_helper_ext_0025_param_2,
	.param .b64 _bpf_helper_ext_0025_param_3,
	.param .b64 _bpf_helper_ext_0025_param_4
)                                       // @_bpf_helper_ext_0025
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<6>;
	.reg .b32 	%r<42>;
	.reg .b64 	%rd<63>;

// %bb.0:
	ld.param.u64 	%rd16, [_bpf_helper_ext_0025_param_1];
	mul.lo.s64 	%rd19, %rd16, 40;
	mov.u64 	%rd20, map_info;
	add.s64 	%rd21, %rd20, %rd19;
	ld.const.u32 	%r9, [%rd21+16];
	setp.ne.s32 	%p1, %r9, 1527;
	@%p1 bra 	$L__BB10_13;
// %bb.1:
	ld.const.v2.u32 	{%r12, %r13}, [%rd21+8];
	cvt.s64.s32 	%rd1, %r13;
	cvt.s64.s32 	%rd30, %r12;
	add.s64 	%rd2, %rd30, 8;
	mul.lo.s64 	%rd31, %rd2, %rd1;
	add.s64 	%rd32, %rd31, 24;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %ntid.x;
	mov.u32 	%r16, %tid.x;
	mad.lo.s32 	%r17, %r14, %r15, %r16;
	mov.u32 	%r18, %ctaid.y;
	mov.u32 	%r19, %ntid.y;
	mov.u32 	%r20, %tid.y;
	mad.lo.s32 	%r21, %r18, %r19, %r20;
	mov.u32 	%r22, %ctaid.z;
	mov.u32 	%r23, %ntid.z;
	mov.u32 	%r24, %tid.z;
	mad.lo.s32 	%r25, %r22, %r23, %r24;
	mov.u32 	%r26, %nctaid.x;
	mul.lo.s32 	%r27, %r26, %r15;
	mov.u32 	%r28, %nctaid.y;
	mul.lo.s32 	%r29, %r28, %r19;
	cvt.s64.s32 	%rd33, %r25;
	mul.wide.s32 	%rd34, %r29, %r27;
	mul.lo.s64 	%rd35, %rd34, %rd33;
	mul.lo.s32 	%r30, %r21, %r27;
	cvt.s64.s32 	%rd36, %r30;
	cvt.s64.s32 	%rd37, %r17;
	add.s64 	%rd38, %rd36, %rd37;
	add.s64 	%rd39, %rd38, %rd35;
	mul.lo.s64 	%rd40, %rd32, %rd39;
	ld.const.u64 	%rd41, [%rd21+24];
	add.s64 	%rd3, %rd41, %rd40;
	ld.u64 	%rd42, [%rd3+8];
	ld.u64 	%rd43, [%rd3];
	sub.s64 	%rd44, %rd42, %rd43;
	setp.eq.s64 	%p2, %rd44, %rd1;
	mov.u64 	%rd62, 2;
	@%p2 bra 	$L__BB10_14;
// %bb.2:
	ld.param.u64 	%rd18, [_bpf_helper_ext_0025_param_4];
	mov.u32 	%r31, 1;
	st.u32 	[%rd3+16], %r31;
	add.s64 	%rd45, %rd3, 8;
	atom.add.u64 	%rd4, [%rd45], 1;
	or.b64  	%rd46, %rd4, %rd1;
	and.b64  	%rd47, %rd46, -4294967296;
	setp.ne.s64 	%p3, %rd47, 0;
	@%p3 bra 	$L__BB10_4;
	bra.uni 	$L__BB10_3;
$L__BB10_4:
	rem.u64 	%rd59, %rd4, %rd1;
	bra.uni 	$L__BB10_5;
$L__BB10_13:
	mov.u64 	%rd23, _$_str1;
	cvta.global.u64 	%rd24, %rd23;
	mov.u64 	%rd25, 0;
	{ // callseq 3, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd24;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd25;
	.param .b32 retval0;
	call.uni (retval0), 
	vprintf, 
	(
	param0, 
	param1
	);
	ld.param.b32 	%r10, [retval0+0];
	} // callseq 3
	mov.u64 	%rd62, 1;
	bra.uni 	$L__BB10_14;
$L__BB10_3:
	cvt.u32.u64 	%r32, %rd1;
	cvt.u32.u64 	%r33, %rd4;
	rem.u32 	%r34, %r33, %r32;
	cvt.u64.u32 	%rd59, %r34;
$L__BB10_5:
	mul.lo.s64 	%rd48, %rd59, %rd2;
	add.s64 	%rd49, %rd3, %rd48;
	st.u64 	[%rd49+24], %rd18;
	cvt.u32.u64 	%r1, %rd18;
	setp.lt.s32 	%p4, %r1, 1;
	mov.u32 	%r38, 0;
	@%p4 bra 	$L__BB10_12;
// %bb.6:
	ld.param.u64 	%rd17, [_bpf_helper_ext_0025_param_3];
	add.s64 	%rd8, %rd49, 32;
	and.b32  	%r40, %r1, 3;
	setp.lt.u32 	%p5, %r1, 4;
	mov.u32 	%r41, %r38;
	@%p5 bra 	$L__BB10_9;
// %bb.7:
	cvt.u64.u32 	%rd51, %r1;
	and.b64  	%rd9, %rd51, 4294967292;
	mov.u64 	%rd60, 0;
	cvt.u32.u64 	%r36, %rd9;
$L__BB10_8:                             // =>This Inner Loop Header: Depth=1
	and.b64  	%rd52, %rd60, 4294967295;
	add.s64 	%rd53, %rd17, %rd60;
	ld.u8 	%rs1, [%rd53];
	add.s64 	%rd54, %rd8, %rd52;
	st.u8 	[%rd54], %rs1;
	ld.u8 	%rs2, [%rd53+1];
	st.u8 	[%rd54+1], %rs2;
	ld.u8 	%rs3, [%rd53+2];
	st.u8 	[%rd54+2], %rs3;
	ld.u8 	%rs4, [%rd53+3];
	st.u8 	[%rd54+3], %rs4;
	add.s64 	%rd60, %rd60, 4;
	cvt.u32.u64 	%r41, %rd60;
	setp.ne.s32 	%p6, %r36, %r41;
	@%p6 bra 	$L__BB10_8;
$L__BB10_9:
	setp.eq.s32 	%p7, %r40, 0;
	@%p7 bra 	$L__BB10_12;
// %bb.10:
	cvt.u64.u32 	%rd55, %r41;
	add.s64 	%rd61, %rd17, %rd55;
$L__BB10_11:                            // =>This Inner Loop Header: Depth=1
	.pragma "nounroll";
	cvt.u64.u32 	%rd56, %r41;
	ld.u8 	%rs5, [%rd61];
	add.s64 	%rd57, %rd8, %rd56;
	st.u8 	[%rd57], %rs5;
	add.s32 	%r41, %r41, 1;
	add.s64 	%rd61, %rd61, 1;
	add.s32 	%r40, %r40, -1;
	setp.ne.s32 	%p8, %r40, 0;
	@%p8 bra 	$L__BB10_11;
$L__BB10_12:
	st.u32 	[%rd3+16], %r38;
	mov.u64 	%rd62, 0;
$L__BB10_14:
	st.param.b64 	[func_retval0+0], %rd62;
	ret;
                                        // -- End function
}
	// .globl	_bpf_helper_ext_0501    // -- Begin function _bpf_helper_ext_0501
.visible .func  (.param .b64 func_retval0) _bpf_helper_ext_0501(
	.param .b64 _bpf_helper_ext_0501_param_0,
	.param .b64 _bpf_helper_ext_0501_param_1,
	.param .b64 _bpf_helper_ext_0501_param_2,
	.param .b64 _bpf_helper_ext_0501_param_3,
	.param .b64 _bpf_helper_ext_0501_param_4
)                                       // @_bpf_helper_ext_0501
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<6>;
	.reg .b32 	%r<15>;
	.reg .b64 	%rd<28>;

// %bb.0:
	ld.param.u64 	%rd11, [_bpf_helper_ext_0501_param_0];
	ld.const.u64 	%rd19, [constData];
	add.s64 	%rd2, %rd19, 24;
	ld.u8 	%rs5, [%rd11];
	setp.eq.s16 	%p1, %rs5, 0;
	mov.u64 	%rd27, 0;
	mov.u64 	%rd25, %rd27;
	@%p1 bra 	$L__BB11_3;
// %bb.1:
	add.s64 	%rd3, %rd11, 1;
	mov.u64 	%rd25, 0;
$L__BB11_2:                             // =>This Inner Loop Header: Depth=1
	add.s64 	%rd14, %rd2, %rd25;
	st.u8 	[%rd14], %rs5;
	add.s64 	%rd15, %rd3, %rd25;
	ld.u8 	%rs5, [%rd15];
	setp.ne.s16 	%p2, %rs5, 0;
	add.s64 	%rd25, %rd25, 1;
	@%p2 bra 	$L__BB11_2;
$L__BB11_3:
	add.s64 	%rd17, %rd2, %rd25;
	mov.u16 	%rs4, 0;
	st.u8 	[%rd17], %rs4;
	mov.u32 	%r6, %tid.x;
	and.b32  	%r1, %r6, 31;
	add.s64 	%rd20, %rd19, 4;
	mov.u32 	%r14, 0;
	add.s64 	%rd18, %rd19, 8;
	mov.u32 	%r12, 501;
	mov.u32 	%r11, 42;
	bra.uni 	$L__BB11_4;
$L__BB11_7:                             //   in Loop: Header=BB11_4 Depth=1
	bar.warp.sync 	%r3;
	add.s32 	%r14, %r14, 1;
	setp.ne.s32 	%p8, %r14, 32;
	@%p8 bra 	$L__BB11_4;
	bra.uni 	$L__BB11_8;
$L__BB11_4:                             // =>This Loop Header: Depth=1
                                        //     Child Loop BB11_5 Depth 2
	// begin inline asm
	activemask.b32 %r3;
	// end inline asm
	shr.u32 	%r8, %r3, %r14;
	and.b32  	%r9, %r8, 1;
	setp.eq.b32 	%p3, %r9, 1;
	not.pred 	%p4, %p3;
	setp.ne.s32 	%p5, %r1, %r14;
	or.pred  	%p6, %p5, %p4;
	@%p6 bra 	$L__BB11_7;
$L__BB11_5:                             //   Parent Loop BB11_4 Depth=1
                                        // =>  This Inner Loop Header: Depth=2
	atom.cas.b32 	%r10, [%rd18], 0, 1;
	setp.eq.s32 	%p7, %r10, 1;
	@%p7 bra 	$L__BB11_5;
// %bb.6:                               //   in Loop: Header=BB11_4 Depth=1
	st.u32 	[%rd19+12], %r12;
	mov.u64 	%rd21, 0;
	st.u64 	[%rd19+16], %rd21;
	// begin inline asm
	.reg .pred p0;                   
	membar.sys;                      
	st.global.u32 [%rd19], 1;           
	spin_wait:                       
	membar.sys;                      
	ld.global.u32 %r11, [%rd20];          
	setp.eq.u32 p0, %r11, 0;           
	@p0 bra spin_wait;               
	st.global.u32 [%rd20], 0;           
	membar.sys;                      
	
	// end inline asm
	ld.u64 	%rd27, [%rd19+2147483680];
	atom.exch.b32 	%r13, [%rd18], 0;
	bra.uni 	$L__BB11_7;
$L__BB11_8:
	cvt.s64.s32 	%rd23, %rd27;
	st.param.b64 	[func_retval0+0], %rd23;
	ret;
                                        // -- End function
}
	// .globl	_bpf_helper_ext_0502    // -- Begin function _bpf_helper_ext_0502
.visible .func  (.param .b64 func_retval0) _bpf_helper_ext_0502(
	.param .b64 _bpf_helper_ext_0502_param_0,
	.param .b64 _bpf_helper_ext_0502_param_1,
	.param .b64 _bpf_helper_ext_0502_param_2,
	.param .b64 _bpf_helper_ext_0502_param_3,
	.param .b64 _bpf_helper_ext_0502_param_4
)                                       // @_bpf_helper_ext_0502
{
	.reg .b64 	%rd<2>;

// %bb.0:
	// begin inline asm
	mov.u64 %rd1, %globaltimer;
	// end inline asm
	st.param.b64 	[func_retval0+0], %rd1;
	ret;
                                        // -- End function
}
	// .globl	_bpf_helper_ext_0503    // -- Begin function _bpf_helper_ext_0503
.visible .func  (.param .b64 func_retval0) _bpf_helper_ext_0503(
	.param .b64 _bpf_helper_ext_0503_param_0,
	.param .b64 _bpf_helper_ext_0503_param_1,
	.param .b64 _bpf_helper_ext_0503_param_2,
	.param .b64 _bpf_helper_ext_0503_param_3,
	.param .b64 _bpf_helper_ext_0503_param_4
)                                       // @_bpf_helper_ext_0503
{
	.reg .b32 	%r<4>;
	.reg .b64 	%rd<8>;

// %bb.0:
	ld.param.u64 	%rd1, [_bpf_helper_ext_0503_param_0];
	ld.param.u64 	%rd2, [_bpf_helper_ext_0503_param_1];
	mov.u32 	%r1, %ctaid.x;
	cvt.u64.u32 	%rd3, %r1;
	ld.param.u64 	%rd4, [_bpf_helper_ext_0503_param_2];
	st.u64 	[%rd1], %rd3;
	mov.u32 	%r2, %ctaid.y;
	cvt.u64.u32 	%rd5, %r2;
	st.u64 	[%rd2], %rd5;
	mov.u32 	%r3, %ctaid.z;
	cvt.u64.u32 	%rd6, %r3;
	st.u64 	[%rd4], %rd6;
	mov.u64 	%rd7, 0;
	st.param.b64 	[func_retval0+0], %rd7;
	ret;
                                        // -- End function
}
	// .globl	_bpf_helper_ext_0504    // -- Begin function _bpf_helper_ext_0504
.visible .func  (.param .b64 func_retval0) _bpf_helper_ext_0504(
	.param .b64 _bpf_helper_ext_0504_param_0,
	.param .b64 _bpf_helper_ext_0504_param_1,
	.param .b64 _bpf_helper_ext_0504_param_2,
	.param .b64 _bpf_helper_ext_0504_param_3,
	.param .b64 _bpf_helper_ext_0504_param_4
)                                       // @_bpf_helper_ext_0504
{
	.reg .b32 	%r<4>;
	.reg .b64 	%rd<8>;

// %bb.0:
	ld.param.u64 	%rd1, [_bpf_helper_ext_0504_param_0];
	ld.param.u64 	%rd2, [_bpf_helper_ext_0504_param_1];
	mov.u32 	%r1, %ntid.x;
	cvt.u64.u32 	%rd3, %r1;
	ld.param.u64 	%rd4, [_bpf_helper_ext_0504_param_2];
	st.u64 	[%rd1], %rd3;
	mov.u32 	%r2, %ntid.y;
	cvt.u64.u32 	%rd5, %r2;
	st.u64 	[%rd2], %rd5;
	mov.u32 	%r3, %ntid.z;
	cvt.u64.u32 	%rd6, %r3;
	st.u64 	[%rd4], %rd6;
	mov.u64 	%rd7, 0;
	st.param.b64 	[func_retval0+0], %rd7;
	ret;
                                        // -- End function
}
	// .globl	_bpf_helper_ext_0505    // -- Begin function _bpf_helper_ext_0505
.visible .func  (.param .b64 func_retval0) _bpf_helper_ext_0505(
	.param .b64 _bpf_helper_ext_0505_param_0,
	.param .b64 _bpf_helper_ext_0505_param_1,
	.param .b64 _bpf_helper_ext_0505_param_2,
	.param .b64 _bpf_helper_ext_0505_param_3,
	.param .b64 _bpf_helper_ext_0505_param_4
)                                       // @_bpf_helper_ext_0505
{
	.reg .b32 	%r<4>;
	.reg .b64 	%rd<8>;

// %bb.0:
	ld.param.u64 	%rd1, [_bpf_helper_ext_0505_param_0];
	ld.param.u64 	%rd2, [_bpf_helper_ext_0505_param_1];
	mov.u32 	%r1, %tid.x;
	cvt.u64.u32 	%rd3, %r1;
	ld.param.u64 	%rd4, [_bpf_helper_ext_0505_param_2];
	st.u64 	[%rd1], %rd3;
	mov.u32 	%r2, %tid.y;
	cvt.u64.u32 	%rd5, %r2;
	st.u64 	[%rd2], %rd5;
	mov.u32 	%r3, %tid.z;
	cvt.u64.u32 	%rd6, %r3;
	st.u64 	[%rd4], %rd6;
	mov.u64 	%rd7, 0;
	st.param.b64 	[func_retval0+0], %rd7;
	ret;
                                        // -- End function
}
	// .globl	_bpf_helper_ext_0506    // -- Begin function _bpf_helper_ext_0506
.visible .func  (.param .b64 func_retval0) _bpf_helper_ext_0506(
	.param .b64 _bpf_helper_ext_0506_param_0,
	.param .b64 _bpf_helper_ext_0506_param_1,
	.param .b64 _bpf_helper_ext_0506_param_2,
	.param .b64 _bpf_helper_ext_0506_param_3,
	.param .b64 _bpf_helper_ext_0506_param_4
)                                       // @_bpf_helper_ext_0506
{
	.reg .b64 	%rd<2>;

// %bb.0:
	// begin inline asm
	membar.sys;                      
	
	// end inline asm
	mov.u64 	%rd1, 0;
	st.param.b64 	[func_retval0+0], %rd1;
	ret;
                                        // -- End function
}
	// .globl	_bpf_helper_ext_0507    // -- Begin function _bpf_helper_ext_0507
.visible .func  (.param .b64 func_retval0) _bpf_helper_ext_0507(
	.param .b64 _bpf_helper_ext_0507_param_0,
	.param .b64 _bpf_helper_ext_0507_param_1,
	.param .b64 _bpf_helper_ext_0507_param_2,
	.param .b64 _bpf_helper_ext_0507_param_3,
	.param .b64 _bpf_helper_ext_0507_param_4
)                                       // @_bpf_helper_ext_0507
{
	.reg .b64 	%rd<2>;

// %bb.0:
	// begin inline asm
	exit;                      
	
	// end inline asm
	mov.u64 	%rd1, 0;
	st.param.b64 	[func_retval0+0], %rd1;
	ret;
                                        // -- End function
}
	// .globl	_bpf_helper_ext_0508    // -- Begin function _bpf_helper_ext_0508
.visible .func  (.param .b64 func_retval0) _bpf_helper_ext_0508(
	.param .b64 _bpf_helper_ext_0508_param_0,
	.param .b64 _bpf_helper_ext_0508_param_1,
	.param .b64 _bpf_helper_ext_0508_param_2,
	.param .b64 _bpf_helper_ext_0508_param_3,
	.param .b64 _bpf_helper_ext_0508_param_4
)                                       // @_bpf_helper_ext_0508
{
	.reg .b32 	%r<4>;
	.reg .b64 	%rd<8>;

// %bb.0:
	ld.param.u64 	%rd1, [_bpf_helper_ext_0508_param_0];
	ld.param.u64 	%rd2, [_bpf_helper_ext_0508_param_1];
	mov.u32 	%r1, %nctaid.x;
	cvt.u64.u32 	%rd3, %r1;
	ld.param.u64 	%rd4, [_bpf_helper_ext_0508_param_2];
	st.u64 	[%rd1], %rd3;
	mov.u32 	%r2, %nctaid.y;
	cvt.u64.u32 	%rd5, %r2;
	st.u64 	[%rd2], %rd5;
	mov.u32 	%r3, %nctaid.z;
	cvt.u64.u32 	%rd6, %r3;
	st.u64 	[%rd4], %rd6;
	mov.u64 	%rd7, 0;
	st.param.b64 	[func_retval0+0], %rd7;
	ret;
                                        // -- End function
}
)";
