name: Build benchmarks

on:
  push:
    branches: "master"
  pull_request:
    branches: "master"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: install deps
      run: |
        sudo apt update
        wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 17
        sudo apt update
        sudo apt install -y --no-install-recommends \
        libelf1 libelf-dev zlib1g-dev make git libboost1.74-all-dev \
        binutils-dev libyaml-cpp-dev  gcc-12 g++-12 llvm-17 clang-17

    - name: verify llvm-17 installation # 增加验证步骤 (可选)
      run: llvm-config-17 --version

    - name: clear cmake cache # 清除 CMake 缓存
      run: rm -rf build

    - name: build runtime
      run:  cmake -Bbuild  -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo \
             -DBUILD_BPFTIME_DAEMON=1 \
             -DLLVM_CONFIG=/usr/lib/llvm-17/bin/llvm-config-17 # 显式指定 llvm-config

    - name: build benchmarks
      run:  make -C benchmark

    # - name: run benchmarks
    #   run:  cd benchmark && python3 run_benchmark.py