name: Build benchmarks

on:
  push:
    branches: "master"
  pull_request:
    branches: "master"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: install deps
      run: |
        sudo apt update
        wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 17
        sudo apt update
        sudo apt install -y --no-install-recommends \
        libelf1 libelf-dev zlib1g-dev make git libboost1.74-all-dev \
        binutils-dev libyaml-cpp-dev  gcc-12 g++-12 llvm-17 clang-17

    - name: build runtime
      run:  CC=gcc-12 CXX=g++-12 make release -j

    - name: build benchmarks
      run:  make -C benchmark

    # - name: run benchmarks
    #   run:  cd benchmark && python3 run_benchmark.py