name: Build and public docker image

on:
  push:
    branches: "master"
  pull_request: 
    branches: "master"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # run only when code is compiling and tests are passing
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build docker
        run: |
          docker build .

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        if:   "github.repository_owner == 'eunomia-bpf' && !startsWith(github.ref, 'refs/pull/')"
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./
          file: Dockerfile
          platforms: linux/amd64
          # Note: tags has to be all lower-case
          tags: |
            ghcr.io/${{ github.repository_owner }}/bpftime:latest
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
