name: Build and test AOT cli

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        runs-on-container:
          - ubuntu:22.04
          - fedora:39
    runs-on: ubuntu-latest
    container: 
      image: ${{matrix.runs-on-container}}
      options: --privileged
    steps:
    - name: Install dependencies (Ubuntu)
      if: startsWith(matrix.runs-on-container,'ubuntu')
      run: | 
        apt-get update
        apt-get install -y binutils-dev libboost1.74-all-dev libelf-dev zlib1g-dev libyaml-cpp-dev gcc-12 g++-12 llvm git make cmake pkg-config clang llvm-15-dev
    - name: Install dependencies (Fedora)
      if: startsWith(matrix.runs-on-container,'fedora')
      run: | 
        dnf install -y make gcc g++ cmake llvm15-devel boost-devel zlib-devel elfutils-libelf-devel pkgconf clang git
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build and install everything (Ubuntu)
      if: startsWith(matrix.runs-on-container,'ubuntu')
      run: |
        CC=gcc-12 CXX=g++-12 make release-with-llvm-jit -j
    - name: Build and install everything (Fedora)
      if: startsWith(matrix.runs-on-container,'fedora')
      run: |
        make release-with-llvm-jit -j
    - name: Do compilation & run
      run: |
        export PATH=$PATH:~/.bpftime
        cd .github/assets
        bpftime-vm build sum.bpf.o
        echo "AwAAAAEAAAACAAAAAwAAAA==" | base64 -d > test.bin
        program_output=$(bpftime-vm run test.o test.bin)
        echo $program_output
        if echo $program_output | grep "Output: 6"; then
          echo "Successful!"
          exit 0
        else
          echo "Not found!"
          exit 1
        fi
        
      