name: Build and Test VM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8' 
    - name: cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
        key: ${{ runner.os }}-dependencies

    - name: install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-arm-linux-gnueabi qemu-user

    - name: build
      run: make build-vm

    - name: install test deps
      run: |
        sudo apt update
        sudo apt install python3
        sudo apt install python3-pytest

    - name: run tests x86
      run: |
        python3.8 -m venv vm/test
        source vm/test/bin/activate
        sudo apt install python3-pytest
        pip install -r vm/test/requirements.txt
        # make build # or build-arm32 build-arm64
        make -C vm test-vm
