name: Build and Test VM

on:
  push:
    branches: [ master ]
    paths:
        - "vm/**"
  pull_request:
    branches: [ master ]
    paths:
        - "vm/**"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - container: ubuntu-2204
            image: manjusakalza/bpftime-base-image:ubuntu-2204
          - container: fedora-39
            image: manjusakalza/bpftime-base-image:fedora-39
          - container: openeuler-2403sp2
            image: openeuler/openeuler:24.03-lts-sp1
    container:
      image: "${{ matrix.image }}"
      options: --privileged
    steps:

    - name: cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
        key: ${{ runner.os }}-dependencies
    - name: Install git (openEuler only)
      if: matrix.container == 'openeuler-2403sp2'
      run: |
        set -e
        if command -v dnf >/dev/null 2>&1; then PM=dnf; else PM=yum; fi
        $PM -y update
        $PM -y install git ca-certificates
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v4
      if: startsWith(matrix.container,'ubuntu')
      with:
        python-version: '3.8'
    - name: Install build deps (openEuler only)
      if: matrix.container == 'openeuler-2403sp2'
      run: |
        set -e
        if command -v dnf >/dev/null 2>&1; then PM=dnf; else PM=yum; fi
        $PM -y install cmake make gcc gcc-c++ clang llvm llvm-devel zlib-devel elfutils-libelf-devel pkgconf-pkg-config
    - name: build
      run: make build-vm
    