name: Run unit tests of llvm-jit

on:
  push:
    branches: "master"
  pull_request: 
    branches: "master"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        container:
          - ubuntu-2204
          - fedora-39
    runs-on: ubuntu-22.04
    container: 
      image: "manjusakalza/bpftime-base-image:${{matrix.container}}"
      options: --privileged
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build and install everything
      run: |
        make build-llvm -j
    - name: Run tests
      run: |
        ./build/vm/llvm-jit/unit-test/llvm_jit_tests

    - name: build llvm JIT/AOT as a standalone library
      run: |
        cd vm/llvm-jit &&\
        cmake -B build -DCMAKE_BUILD_TYPE=Release &&\
        cmake --build build --target all -j

    - name: build vm as a standalone library
      run: |
        cd vm && make build-llvm -j     
