name: Build and Test VM

on:
  push:
    branches: [ master ]
    paths:
        - "vm/**"
  pull_request:
    branches: [ master ]
    paths:
        - "vm/**"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - container: ubuntu-2204
            image: manjusakalza/bpftime-base-image:ubuntu-2204
          - container: fedora-39
            image: manjusakalza/bpftime-base-image:fedora-39
    container:
      image: "${{ matrix.image }}"
      options: --privileged
    steps:

    - name: cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
        key: ${{ runner.os }}-dependencies
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v4
      if: startsWith(matrix.container,'ubuntu')
      with:
        python-version: '3.8'
    - name: build
      run: make build-vm
    - name: Build runtime tests (Ubuntu/Fedora only)
      if: matrix.container != 'openeuler-2403sp2'
      run: |
        set -e
        cmake -B build -DBPFTIME_ENABLE_UNIT_TESTING=1 -DCMAKE_BUILD_TYPE=Debug
        cmake --build build --config Debug --target bpftime_runtime_tests -j$(nproc)
    - name: Test runtime with llvm_vm (Ubuntu/Fedora only)
      if: matrix.container != 'openeuler-2403sp2'
      env:
        BPFTIME_VM_NAME: llvm
      run: ./build/runtime/unit-test/bpftime_runtime_tests
    - name: Test runtime with ubpf_vm (Ubuntu/Fedora only)
      if: matrix.container != 'openeuler-2403sp2'
      env:
        BPFTIME_VM_NAME: ubpf
      run: ./build/runtime/unit-test/bpftime_runtime_tests
    